{
    "source_id": "vcdb",
    "timeline": {
        "incident": {
            "year": 2020,
            "month": 7
        }
    },
    "victim": {
        "government": [
            "NA"
        ],
        "country": [
            "JP"
        ],
        "victim_id": "Konica Minolta",
        "employee_count": "25001 to 50000",
        "industry": "423420",
        "locations_affected": 1
    },
    "action": {
        "hacking": {
            "variety": [
                "Unknown"
            ],
            "vector": [
                "Unknown"
            ]
        },
        "malware": {
            "variety": [
                "Ransomware"
            ],
            "vector": [
                "Unknown"
            ],
            "name": "RansomEXX"
        }
    },
    "actor": {
        "external": {
            "variety": [
                "Organized crime"
            ],
            "motive": [
                "Financial"
            ]
        }
    },
    "asset": {
        "assets": [
            {
                "variety": "S - Unknown"
            }
        ],
        "cloud": [
            "Unknown"
        ],
        "role": [
            "IT"
        ]
    },
    "attribute": {
        "confidentiality": {
            "data_disclosure": "Potentially"
        },
        "integrity": {
            "variety": [
                "Software installation"
            ]
        },
        "availability": {
            "variety": [
                "Obscuration"
            ]
        }
    },
    "discovery_method": {
        "external": {
            "variety": [
                "Actor disclosure"
            ]
        }
    },
    "value_chain": {
        "cash-out": {
            "variety": [
                "Cryptocurrency"
            ]
        }
    },
    "plus": {
        "event_chain": [
            {
                "action": "hak",
                "actor": "ext",
                "asset": "srv",
                "attribute": "ia",
                "summary": "Actors got into the environment"
            },
            {
                "action": "mal",
                "actor": "ext",
                "asset": "srv",
                "attribute": "ia",
                "summary": "malware installed"
            },
            {
                "action": "mal",
                "actor": "ext",
                "asset": "srv",
                "attribute": "au",
                "summary": "ransomware encrypted stuff"
            }
        ],
        "modified": "2021-07-27T00:00:39.038Z",
        "created": "2021-07-27T00:00:39.038Z",
        "timeline": {
            "notification": {
                "year": 2020,
                "month": 8,
                "day": 16
            }
        },
        "master_id": "18ee6fe5-f180-49f1-8135-17a9640a8ad2",
        "analysis_status": "Reviewed",
        "analyst": "planglois",
        "dbir_year": 2022,
        "github": "16102"
    },
    "incident_id": "214351f0-ee4b-11eb-a0c0-efc7cda0e23f",
    "security_incident": "Confirmed",
    "reference": "https://www.bleepingcomputer.com/news/security/business-technology-giant-konica-minolta-hit-by-new-ransomware/",
    "summary": "Business technology giant Konica Minolta hit by new ransomware",
    "confidence": "High",
    "targeted": "Unknown",
    "schema_version": "1.3.5"
}